

# --- package path bootstrap -------------------------------------------------
import os as _os
from pathlib import Path as _Path


def _repro_root(start=None):
    """Package root, located by the '.repro_root' marker (or REPRO_ROOT env)."""
    here = _Path(start or __file__).resolve()
    for cand in [here, *here.parents]:
        if (cand / ".repro_root").exists():
            return cand
    return _Path(_os.environ.get("REPRO_ROOT", _Path.cwd())).resolve()


REPRO_ROOT = _repro_root()
# ---------------------------------------------------------------------------
import pandas as pd
rows = [
 dict(dataset="Renal",selector="ElasticNet+SIS Reference",k=50,
      Q2_status="COMPLETE_MATCHED_EXISTING",
      Q3_semantic_status="DEVELOPMENT_1000_COMPLETE_FINAL_EXTERNAL_MISSING",
      Q3_random_status="FINAL_EXTERNAL_1000x2_COMPLETE",
      Q3_final_null_status="SEMANTIC_FINAL_RECONSTRUCTABLE_ZERO_COST",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="COMPLETE",
      Q5_status="INDEPENDENT_EXTERNAL_COMPLETE_POSITIVE_POINT_ESTIMATE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="100 Selective + 100 Global matched formal pairs; semantic shuffle reselects lambda per replicate but original file stores dev metrics only. External dataset already unsealed and random-null script proves zero-cost external evaluation path. Q4 existing deterministic audit."),
 dict(dataset="GSE272769",selector="ElasticNet",k=50,
      Q2_status="MISSING_STRICT_MATCHED_GLOBAL",
      Q3_semantic_status="COMPLETE_200_NESTED_STRONG",
      Q3_random_status="MISSING",
      Q3_final_null_status="NO_INDEPENDENT_FINAL; NESTED_OUTER_CV_IS_FINAL_EVAL",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="COMPLETE_ACTIVE_FOLD_AUDIT",
      Q5_status="STRICT_NESTED_OUTER_CV_COMPLETE_POSITIVE",
      cache_sufficient="PARTIAL_FOR_Q2; YES_FOR_Q3_RANDOM",
      new_llm_calls_needed="Q2_LIKELY_YES_AFTER_CACHE_AUDIT",
      notes="Formal focus ElasticNet k=50 only. Existing measurement pool is selective-routing union, not a strict data-confusion-independent global graph. Q3 random can be generated without LLM and must reselect lam within each replicate."),
 dict(dataset="Breast",selector="LASSO",k=10,
      Q2_status="MISSING_STRICT_MATCHED_OBJECTIVE_BUT_BROAD_CACHE_SUFFICIENT",
      Q3_semantic_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_random_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_final_null_status="COMPLETE",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="COMPLETE",
      Q5_status="SEALED_EXTERNAL_COMPLETE_POSITIVE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Formal report must exclude k=30. Existing global/global_certainty broad cache is much larger than selective; strict Q2 needs same-objective, same-budget broad subsampling rather than comparing legacy global/global_certainty directly."),
 dict(dataset="Breast",selector="LASSO",k=20,
      Q2_status="MISSING_STRICT_MATCHED_OBJECTIVE_BUT_BROAD_CACHE_SUFFICIENT",
      Q3_semantic_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_random_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_final_null_status="COMPLETE",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="NOT_YET_REPORTED_FOR_THIS_CELL",
      Q5_status="SEALED_EXTERNAL_COMPLETE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Formal k in {10,20}. Extend Q4 if exact frozen support/objective artifacts permit."),
 dict(dataset="Breast",selector="ElasticNet",k=10,
      Q2_status="MISSING_STRICT_MATCHED_OBJECTIVE_BUT_BROAD_CACHE_SUFFICIENT",
      Q3_semantic_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_random_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_final_null_status="COMPLETE",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="COMPLETE",
      Q5_status="SEALED_EXTERNAL_COMPLETE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Strict matched Q2 should reuse cached broad measurements with same Selective query budget and current selective correction objective."),
 dict(dataset="Breast",selector="ElasticNet",k=20,
      Q2_status="MISSING_STRICT_MATCHED_OBJECTIVE_BUT_BROAD_CACHE_SUFFICIENT",
      Q3_semantic_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_random_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_final_null_status="COMPLETE",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="NOT_YET_REPORTED_FOR_THIS_CELL",
      Q5_status="SEALED_EXTERNAL_COMPLETE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Formal k in {10,20}."),
 dict(dataset="Breast",selector="SIS",k=10,
      Q2_status="MISSING_STRICT_MATCHED_OBJECTIVE_BUT_BROAD_CACHE_SUFFICIENT",
      Q3_semantic_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_random_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_final_null_status="COMPLETE",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="COMPLETE",
      Q5_status="SEALED_EXTERNAL_COMPLETE_POSITIVE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Priority Q2 cell per request."),
 dict(dataset="Breast",selector="SIS",k=20,
      Q2_status="MISSING_STRICT_MATCHED_OBJECTIVE_BUT_BROAD_CACHE_SUFFICIENT",
      Q3_semantic_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_random_status="COMPLETE_1000_WITH_SEALED_EXTERNAL",
      Q3_final_null_status="COMPLETE",
      Q4_compatible="YES_CURRENT_OBJECTIVE_THEOREM_COMPATIBLE",
      Q4_status="COMPLETE",
      Q5_status="SEALED_EXTERNAL_COMPLETE_POSITIVE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Priority Q2 cell per request."),
 dict(dataset="CREDIT-G",selector="GBM-permutation",k=10,
      Q2_status="LEGACY_BROAD_EXISTS_STRICT_MATCHED_Q2_MISSING",
      Q3_semantic_status="COMPLETE_1000",
      Q3_random_status="COMPLETE_1000",
      Q3_final_null_status="HOLDOUT_REPLICATE_RESULTS_AVAILABLE",
      Q4_compatible="NO_LEGACY_selective_IS_ADDITIVE_RANK_UTILITY_NOT_CE_CORRECTION",
      Q4_status="MIGRATION_REQUIRED",
      Q5_status="LOCKED_HOLDOUT_COMPLETE_POSITIVE",
      cache_sufficient="YES_FOR_MATCHED_Q2_AND_MIGRATION",new_llm_calls_needed="NO",
      notes="Use term GBM-permutation. Only one selective eligible pair is actionable for this selector. Migrate frozen data score/routing/cached measurement to theorem-compatible correction, tune trust on development only; any post-unseal holdout evaluation of migrated objective is diagnostic."),
 dict(dataset="CREDIT-G",selector="Elastic Net",k=10,
      Q2_status="LEGACY_BROAD_EXISTS_STRICT_MATCHED_Q2_MISSING",
      Q3_semantic_status="COMPLETE_1000",
      Q3_random_status="COMPLETE_1000",
      Q3_final_null_status="HOLDOUT_REPLICATE_RESULTS_AVAILABLE",
      Q4_compatible="NO_LEGACY_selective_IS_ADDITIVE_RANK_UTILITY_NOT_CE_CORRECTION",
      Q4_status="MIGRATION_REQUIRED",
      Q5_status="LOCKED_HOLDOUT_COMPLETE_POSITIVE",
      cache_sufficient="YES_FOR_MATCHED_Q2_AND_MIGRATION",new_llm_calls_needed="NO",
      notes="All three evidence-eligible selective pairs actionable. Same chronology caveat for post-hoc theorem-objective migration."),
 dict(dataset="Hospital Osteoporosis",selector="L1 logistic rank",k=5,
      Q2_status="LEGACY_BROAD_EXISTS_STRICT_MATCHED_OBJECTIVE_MISSING",
      Q3_semantic_status="DEVELOPMENT_1000_COMPLETE",
      Q3_random_status="DEVELOPMENT_1000_COMPLETE",
      Q3_final_null_status="TEMPORAL_FINAL_RECONSTRUCTABLE_FROM_SUPPORT_MAP",
      Q4_compatible="YES_EXACT_NORMALIZED_CE_OBJECTIVE",
      Q4_status="MISSING_ZERO_COST_RESCALING_AUDIT",
      Q5_status="TEMPORAL_EXTERNAL_COMPLETE_NEGATIVE_POINT_ESTIMATE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Primary Q5 k=5 is negative; retain. Broad complete graph cache and selective cache exist. Q3 final can evaluate frozen null supports on Batch2 without retuning."),
 dict(dataset="Hospital Osteoporosis",selector="L1 logistic rank",k=10,
      Q2_status="LEGACY_BROAD_EXISTS_STRICT_MATCHED_OBJECTIVE_MISSING",
      Q3_semantic_status="DEVELOPMENT_1000_COMPLETE",
      Q3_random_status="DEVELOPMENT_1000_COMPLETE",
      Q3_final_null_status="TEMPORAL_FINAL_RECONSTRUCTABLE_FROM_SUPPORT_MAP",
      Q4_compatible="YES_EXACT_NORMALIZED_CE_OBJECTIVE",
      Q4_status="MISSING_ZERO_COST_RESCALING_AUDIT",
      Q5_status="TEMPORAL_EXTERNAL_COMPLETE_POSITIVE_POINT_ESTIMATE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Primary temporal-positive cell. Existing support maps enable final null distribution."),
 dict(dataset="Darmanis GBM",selector="SIS",k=10,
      Q2_status="BROAD_CACHE_EXISTS_STRICT_MATCHED_OBJECTIVE_MISSING",
      Q3_semantic_status="COMPLETE_1000_INTERNAL_GROUPED",
      Q3_random_status="COMPLETE_1000_INTERNAL_GROUPED",
      Q3_final_null_status="NO_INDEPENDENT_FINAL_COHORT",
      Q4_compatible="LIKELY_YES_NEEDS_OBJECTIVE_SCALE_AUDIT",
      Q4_status="MISSING",
      Q5_status="INTERNAL_PLATE_GROUPED_ONLY_POSITIVE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Not patient-level generalization. Broad production cache is large. Priority Q2/Q4 cell."),
 dict(dataset="Darmanis GBM",selector="SIS",k=20,
      Q2_status="BROAD_CACHE_EXISTS_STRICT_MATCHED_OBJECTIVE_MISSING",
      Q3_semantic_status="COMPLETE_1000_INTERNAL_GROUPED",
      Q3_random_status="COMPLETE_1000_INTERNAL_GROUPED",
      Q3_final_null_status="NO_INDEPENDENT_FINAL_COHORT",
      Q4_compatible="LIKELY_YES_NEEDS_OBJECTIVE_SCALE_AUDIT",
      Q4_status="MISSING",
      Q5_status="INTERNAL_PLATE_GROUPED_ONLY_POSITIVE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Priority Q2/Q4 cell."),
 dict(dataset="Darmanis GBM",selector="Elastic Net",k=10,
      Q2_status="BROAD_CACHE_EXISTS_STRICT_MATCHED_OBJECTIVE_MISSING",
      Q3_semantic_status="COMPLETE_1000_INTERNAL_GROUPED",
      Q3_random_status="COMPLETE_1000_INTERNAL_GROUPED",
      Q3_final_null_status="NO_INDEPENDENT_FINAL_COHORT",
      Q4_compatible="LIKELY_YES_NEEDS_OBJECTIVE_SCALE_AUDIT",
      Q4_status="MISSING",
      Q5_status="INTERNAL_PLATE_GROUPED_ONLY_POSITIVE",
      cache_sufficient="YES",new_llm_calls_needed="NO",
      notes="Priority Q2/Q4 cell.")
]
df=pd.DataFrame(rows)
out=str(REPRO_ROOT / '08_diagnostics/q3_q4/05_summary/Q2_Q5_COMPLETION_INVENTORY.csv')
df.to_csv(out,index=False)
print(df.to_string(index=False))
print("\nWROTE",out)
