#!/usr/bin/env python3

# --- package path bootstrap -------------------------------------------------
import os as _os
from pathlib import Path as _Path


def _repro_root(start=None):
    """Package root, located by the '.repro_root' marker (or REPRO_ROOT env)."""
    here = _Path(start or __file__).resolve()
    for cand in [here, *here.parents]:
        if (cand / ".repro_root").exists():
            return cand
    return _Path(_os.environ.get("REPRO_ROOT", _Path.cwd())).resolve()


REPRO_ROOT = _repro_root()
# ---------------------------------------------------------------------------
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor,as_completed
import json,math,hashlib,time,warnings
warnings.filterwarnings('ignore')
import numpy as np,pandas as pd
from scipy.optimize import minimize
from scipy.special import expit
from scipy.stats import rankdata,norm
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

PKG=Path(str(REPRO_ROOT / 'GBM_REPRO_PACKAGE_V2_9_20260919'))
BASE=PKG/'PROJECT/GBM_EXTERNAL_EVIDENCE_20260917/10_LLM_MEASUREMENT/DUAL_METHOD_DESIGN_V2_6'
CONF=BASE/'DATA_CONFUSION_V2_7'; DOWN=BASE/'DOWNSTREAM_V2_9'
ROOT=Path(str(REPRO_ROOT / 'gbm_canonical_recovery_20260917'))
OUT=Path(str(REPRO_ROOT / '08_diagnostics/q3_q4'))
SEM=OUT/'01_q3_semantic_shuffle/DARMANIS_GBM';RND=OUT/'02_q3_random_null/DARMANIS_GBM'
SEM.mkdir(parents=True,exist_ok=True);RND.mkdir(parents=True,exist_ok=True)
SEED=2026091817;NREP=1000;LAMS=[0,0.03,0.1,0.3,1,3,10]
NULL_SEEDS={'semantic':2026092205,'random':2026092206}
CELLS=[('SIS',10),('SIS',20),('ELASTICNET',10)]
selpar={'ELASTICNET':{'C':0.1,'l1_ratio':0.8}}

X=np.load(ROOT/'canonical/X_candidate_aligned_log1p.npy').astype(float)
y=pd.read_csv(ROOT/'canonical/y_canonical.csv')['y'].to_numpy(int)
mp=pd.read_csv(ROOT/'canonical/cell_sample_mapping_canonical.csv')
ann=pd.read_csv(ROOT/'metadata/darmanis_cell_annotation.csv')[['cell_key','plate']]
groups=mp.merge(ann,left_on='cell_id',right_on='cell_key',how='left',validate='one_to_one')['plate'].astype(str).to_numpy()
splits=list(StratifiedGroupKFold(n_splits=5,shuffle=True,random_state=SEED).split(X,y,groups))
P=X.shape[1]

def sis_score(tr):
    xx=X[tr];yy=y[tr];yc=yy-yy.mean();xc=xx-xx.mean(0);den=np.sqrt((xc*xc).sum(0)*(yc*yc).sum())
    return np.nan_to_num(np.abs((xc*yc[:,None]).sum(0)/np.where(den==0,np.nan,den)),nan=0.)
def en_score(tr,fold):
    sc=StandardScaler().fit(X[tr]);Xt=sc.transform(X[tr])
    mod=LogisticRegression(C=.1,solver='saga',class_weight='balanced',penalty='elasticnet',l1_ratio=.8,max_iter=6000,tol=2e-4,random_state=SEED+fold,n_jobs=1)
    mod.fit(Xt,y[tr]);return np.abs(mod.coef_[0])
def anchor(D):
    r=rankdata(-D,method='average');u=1-(r-.5)/len(D);return norm.ppf(np.clip(u,1e-6,1-1e-6))
Ds={}
for fi,(tr,va) in enumerate(splits,1):
    Ds[(fi,'SIS')]=sis_score(tr);Ds[(fi,'ELASTICNET')]=en_score(tr,fi)

# Cached measurement table generated by authoritative v2.9 code.
M=pd.read_csv(DOWN/'selective_COMPLETE_PAIR_SOURCE_MEASUREMENTS_V2_9.csv')
M['key']=list(zip(M.node_i.astype(int),M.node_j.astype(int),M.arm.astype(str)))
mmap={k:(float(yv),float(cv)) for k,yv,cv in zip(M.key,M.y,M.c)}
arms=sorted(M.arm.unique())
keys_by_arm={a:[k for k in mmap if k[2]==a] for a in arms}

# Fixed route geometry for each requested cell.
geom={}
for selector,k in CELLS:
    z=pd.read_csv(CONF/f'{selector}_K{k}_PAIR_CONFUSION_V2_7.csv')
    z=z[z.pair_type=='ACTIONABLE_BOUNDARY_CONFUSION'].copy()
    rows=[]
    for r in z.itertuples():
        i,j=int(r.node_i),int(r.node_j);avail=[a for a in arms if (i,j,a) in mmap];m=len(avail)
        if m==0:continue
        for a in avail:rows.append((i,j,a,float(r.actionable_boundary_score)/m))
    geom[(selector,k)]=rows

def topk(z,D,k):return np.lexsort((np.arange(len(z)),-D,-z))[:k]
def solve(sd,cons,lam):
    if lam==0 or not cons:return sd.copy()
    ii=np.array([r[0] for r in cons],int);jj=np.array([r[1] for r in cons],int);yy=np.array([r[2] for r in cons]);w=np.array([r[3] for r in cons])
    W=float(w.sum())
    if W<=0:return sd.copy()
    active=np.unique(np.r_[ii,jj]);pos={v:q for q,v in enumerate(active)};li=np.array([pos[v] for v in ii]);lj=np.array([pos[v] for v in jj]);base=sd[active].copy()
    def fg(v):
        d=v[li]-v[lj];ce=np.logaddexp(0,d)-yy*d;diff=v-base
        f=.5*np.dot(diff,diff)/P+lam*np.dot(w,ce)/(W+1e-12)
        g=diff/P;rr=lam*(w/(W+1e-12))*(expit(d)-yy);np.add.at(g,li,rr);np.add.at(g,lj,-rr);return float(f),g
    r=minimize(lambda v:fg(v)[0],base,jac=lambda v:fg(v)[1],method='L-BFGS-B',options={'maxiter':500,'maxls':50,'ftol':1e-12,'gtol':1e-8})
    if not r.success:
        x0=r.x if np.all(np.isfinite(r.x)) else base
        r=minimize(lambda v:fg(v)[0],x0,jac=lambda v:fg(v)[1],method='L-BFGS-B',options={'maxiter':3000,'maxls':300,'ftol':1e-13,'gtol':1e-7})
    if not r.success:
        x0=r.x if np.all(np.isfinite(r.x)) else base
        r=minimize(lambda v:fg(v)[0],x0,jac=lambda v:fg(v)[1],method='BFGS',options={'maxiter':3000,'gtol':1e-7})
    if (not r.success) and (not np.all(np.isfinite(r.x))):raise RuntimeError(str(r.message))
    z=sd.copy();z[active]=r.x;return z

def eval_support(fi,ids,cache):
    key=(fi,tuple(sorted(ids.tolist())))
    if key in cache:return cache[key]
    tr,va=splits[fi-1];sc=StandardScaler().fit(X[tr][:,ids])
    mod=LogisticRegression(C=1.,penalty='l2',solver='lbfgs',class_weight='balanced',max_iter=5000,random_state=SEED)
    mod.fit(sc.transform(X[tr][:,ids]),y[tr]);p=mod.predict_proba(sc.transform(X[va][:,ids]))[:,1]
    cache[key]=float(roc_auc_score(y[va],p));return cache[key]

def true_constraints(cell):
    out=[]
    for i,j,a,Adiv in geom[cell]:
        yy,c=mmap[(i,j,a)];out.append((i,j,yy,Adiv*c))
    return out

def null_measurement(mode,rep):
    rng=np.random.default_rng(np.random.SeedSequence([NULL_SEEDS[mode],rep]))
    nm={}
    if mode=='semantic':
        hashes=[]
        for a in arms:
            ks=keys_by_arm[a];perm=rng.permutation(len(ks));hashes.append(perm.tobytes())
            for target_idx,k in enumerate(ks):nm[k]=mmap[ks[int(perm[target_idx])]]
        token=hashlib.sha256(b''.join(hashes)).hexdigest()
    else:
        vals=[]
        for a in arms:
            for k in keys_by_arm[a]:
                p=float(rng.uniform());H=-(p*math.log(max(p,1e-12),2)+(1-p)*math.log(max(1-p,1e-12),2));c=1-H;nm[k]=(1.0 if p>.5 else 0.0,c);vals.append(p)
        token=hashlib.sha256(np.asarray(vals,float).tobytes()).hexdigest()
    return nm,token

def constraints(cell,nm):
    return [(i,j,nm[(i,j,a)][0],Adiv*nm[(i,j,a)][1]) for i,j,a,Adiv in geom[cell]]

sel=pd.read_csv(DOWN/'selective_SELECTED_ETA_V2_9.csv');curves=pd.read_csv(DOWN/'selective_ETA_CURVES_V2_9.csv')
obs={}
for cell in CELLS:
    s,k=cell;r=sel[(sel.selector==s)&(sel.k==k)].iloc[0];ref=float(curves[(curves.selector==s)&(curves.k==k)&np.isclose(curves.lam,0)].iloc[0].mean_auroc)
    obs[cell]={'lam':float(r.lam),'auc':float(r.mean_auroc),'ref':ref,'delta':float(r.mean_auroc-ref)}

# identity gate exact original true constraints
cache0={};idrows=[]
for cell in CELLS:
    vals=[]
    for lam in LAMS:
        av=[]
        for fi,(tr,va) in enumerate(splits,1):
            D=Ds[(fi,cell[0])];z=solve(anchor(D),true_constraints(cell),lam);av.append(eval_support(fi,topk(z,D,cell[1]),cache0))
        vals.append((lam,float(np.mean(av))))
    best=max(v for _,v in vals);chosen=min(e for e,v in vals if np.isclose(v,best,atol=1e-12,rtol=0))
    O=obs[cell];idrows.append({'selector':cell[0],'k':cell[1],'expected_lam':O['lam'],'reproduced_lam':chosen,'expected_auc':O['auc'],'reproduced_auc':best,
                              'pass':bool(np.isclose(chosen,O['lam']) and np.isclose(best,O['auc'],atol=1e-10))})
idc=pd.DataFrame(idrows)
for d in [SEM,RND]:idc.to_csv(d/'IDENTITY_REPRODUCTION.csv',index=False)
if not idc['pass'].all():raise RuntimeError('GBM identity gate failed')

def run_chunk(mode,reps):
    cache={};rows=[]
    for rep in reps:
        nm,token=null_measurement(mode,rep)
        for cell in CELLS:
            cc=constraints(cell,nm);vals=[]
            for lam in LAMS:
                av=[]
                for fi,(tr,va) in enumerate(splits,1):
                    D=Ds[(fi,cell[0])];z=solve(anchor(D),cc,lam);av.append(eval_support(fi,topk(z,D,cell[1]),cache))
                vals.append((lam,float(np.mean(av))))
            best=max(v for _,v in vals);chosen=min(e for e,v in vals if np.isclose(v,best,atol=1e-12,rtol=0));O=obs[cell]
            rows.append({'replicate':rep,'selector':cell[0],'k':cell[1],'mode':mode,'draw_sha256':token,'chosen_lam':chosen,'best_dev_auc':best,
                         'dev_improvement':best-O['ref'],'fixed_observed_lam':O['lam'],'fixed_lam_dev_auc':dict(vals)[O['lam']],
                         'fixed_dev_improvement':dict(vals)[O['lam']]-O['ref']})
    return rows

def run(mode,outdir):
    chunks=[list(range(i,NREP,8)) for i in range(8)];rows=[];t=time.time()
    with ProcessPoolExecutor(max_workers=8) as ex:
        fs=[ex.submit(run_chunk,mode,ch) for ch in chunks]
        for n,f in enumerate(as_completed(fs),1):
            rows.extend(f.result());pd.DataFrame(rows).to_csv(outdir/'PARTIAL.csv',index=False);print(mode,'chunks',n,'/8 rows',len(rows),'sec',round(time.time()-t,1),flush=True)
    R=pd.DataFrame(rows).sort_values(['replicate','selector','k']);R.to_csv(outdir/'REPLICATES_1000.csv',index=False)
    ss=[]
    for cell in CELLS:
        q=R[(R.selector==cell[0])&(R.k==cell[1])];O=obs[cell];v=q.dev_improvement;fx=q.fixed_dev_improvement
        ss.append({'dataset':'Darmanis GBM','selector':cell[0],'k':cell[1],'mode':mode,'n_replicates':NREP,'seed':NULL_SEEDS[mode],
                   'observed_lam':O['lam'],'reference_dev_auc':O['ref'],'observed_dev_auc':O['auc'],'observed_dev_improvement':O['delta'],
                   'null_mean':float(v.mean()),'null_sd':float(v.std(ddof=1)),'null_q95':float(v.quantile(.95)),
                   'observed_percentile':100*float(np.mean(v<=O['delta'])),'empirical_p_one_sided':float((1+int((v>=O['delta']-1e-12).sum()))/(NREP+1)),
                   'fixed_null_mean':float(fx.mean()),'fixed_null_q95':float(fx.quantile(.95)),
                   'fixed_empirical_p_one_sided':float((1+int((fx>=O['delta']-1e-12).sum()))/(NREP+1)),
                   'lam_counts':json.dumps({str(k):int(vv) for k,vv in q.chosen_lam.value_counts().sort_index().items()})})
    S=pd.DataFrame(ss);S.to_csv(outdir/'SUMMARY.csv',index=False)
    (outdir/'SUMMARY.json').write_text(json.dumps({'design':'within-source complete cached (hard direction, certainty) bundle permutation across fixed eligible pair-source identities' if mode=='semantic' else 'fixed routed pair-source identities/evidence eligibility; iid p~U(0,1), hard direction and certainty recomputed',
        'development_tuning':'original five plate-grouped folds; lam reselected per replicate','new_llm_calls':0,'note':'same internal CV folds are used for lam tuning and summarized utility, matching authoritative v2.9 diagnostic','summary':ss},indent=2))

run('semantic',SEM);run('random',RND)
